import { Inter } from "next/font/google";
import "./globals.css";
import "../lib/animate/animate.min.css";
import "../lib/owlcarousel/assets/owl.carousel.min.css";
import "../css/bootstrap.min.css";
import "../css/style.css";
import CustomNavbar from "@/components/navbar";
import FooterComponent from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta charset="utf-8"/>
        <title>Newsers - Free HTML Magazine Template</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
        <meta content="" name="keywords"/>
        <meta content="" name="description"/>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@100;600;800&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <link href="lib/animate/animate.min.css" rel="stylesheet"/> 
        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet"/>
        <link href="css/bootstrap.min.css" rel="stylesheet"/>
        <link href="css/style.css" rel="stylesheet"/>
        <script async src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <script async src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script async src="../lib/easing/easing.min.js"></script>
        <script async src="../lib/waypoints/waypoints.min.js"></script>
        <script async src="../lib/owlcarousel/owl.carousel.min.js"></script>
        <script async src="../js/main.js"></script>
      </head>
      <body >

        <CustomNavbar />
        {children}
        <FooterComponent/>
      </body>
    </html>
  );
}
